### ISSUE TITLE
PersonList without @Bindable

### ISSUE THREAD

**Issue by avario** [trozware/swiftui-data-flow#1]
Hi! I really enjoyed your article!

I think I might have another way to setup the example in *ObservableObject & @ObservedObject - Part 2*. I wasn't sure how else to share this so I thought I'd just create an issue here.

I think `PersonDetailView(person: self.$personList.persons[index])` is actually creating a binding to your `PersonListModel`, rather than to the `PersonViewModel` itself. This means that anytime the `PersonViewModel` is changed on the next screen, it will update the `PersonListModel`, which will cause `PersonListView` to update. This means that the entire list will need to be updated any time a person is modified.

Instead, I think your first approach might have been better - where `PersonDetailView` doesn't require a binding, but instead observes a `PersonViewModel` with `@ObservedObject`. Then to make sure the changes to the `PersonViewModel` are reflected in the `PersonListView`, you could create a new `View` for the list rows and have this observe your `PersonViewModel`:

```swift
struct PersonRow: View {
    @ObservedObject var person: PersonViewModel

    var body: some View {
        Text("\(person.first) \(person.last)")
    }
}
````
```swift
...
ForEach(personList.persons) { person in
    NavigationLink(destination:  PersonDetailView(person: person) ) {
        PersonRow(person: person)
    }
}
...
```

Now whenever a person is modified, only the view for that row is updated, instead of the entire list.

**Comment by dhoerl** [comment]
@avario I tried several variations on Sarah's various attempts to try and find a better approach - then I found yours here. I really really like it - its simple and in my testing works perfectly. In case anyone else comes here, you need to revert the view too:

```
struct PersonDetailView: View {
    //@Binding var person: PersonViewModel
    @ObservedObject var person: PersonViewModel

```

Also, the PersonRow struct can be declared inside the PersonListView to name space it.

For the preview, this line:
return PersonDetailView(person: .constant(person))
must be changed to:
return PersonDetailView(person: person)
