### ISSUE TITLE
Observable 1 but with an array of colors

### ISSUE THREAD

**Issue by dhoerl** [trozware/swiftui-data-flow#2]
Not really an issue, its the only place I can make a comment on the source.

I wanted to see if everything worked if I turned foreground colors into an array as opposed to three different @Published variables:

```
#if false
    @Published var foregroundRed = 0.0
    @Published var foregroundGreen = 0.0
    @Published var foregroundBlue = 0.0
#else
    @Published var foreground: [Double] = [0, 0, 0]
#endif

```

Glad to say it works fine. I believe using structs and collections is a more real-world case.

**Comment by trozware** [comment]
Yes, I would probably use a struct in a real app, but as a demonstration, I felt it more important to be clear.
