### ISSUE TITLE
Suggestion about ObservableObject & @ObservedObject - Part 2

### ISSUE THREAD

**Issue by ig0r8** [trozware/swiftui-data-flow#4]
Hi,
Thanks for writing the "SwiftUI Data Flow" article.

As a follow-up question, why don't you pass the `personList` ObservedObject to the `DetailView`? You also have a UUID for every person, which you can use to identify the element you want to update in the `personList.persons` array.

The main view `NavigationLink` can pass that data:
```Swift
ForEach(personList.persons) { person in
    NavigationLink(destination: PersonDetailView(personList: personList, personID: person.id) ) {
        Text("\(person.first) \(person.last)")
    }
}
```
The `PersonDetailView`:
```Swift
struct PersonDetailView: View {
    @ObservedObject var personList: PersonListModel
    let personID: UUID

    var personIndex: Int {
        //Optional unwrap with fatalError().
        personList.persons.firstIndex(where: { $0.id == personID })!
    }

var body: some View {
...
```
You can update values like this:
```Swift
TextField("Address", text: $personList.persons[personIndex].address)
    .autocapitalization(.words)
```
And both the `PersonDetailView` and the `PersonListView` values will be updated.

**Comment by nkalvi** [comment]
> ```swift
> var personIndex: Int {
>         //Optional unwrap with fatalError().
>         personList.persons.firstIndex(where: { $0.id == personID })!
>     }
> ```

Compiler reports the following errors:
```
- Cannot convert return expression of type 'Dictionary<UUID, PersonViewModel>.Index' to return type 'Int'
- Value of tuple type 'Dictionary<UUID, PersonViewModel>.Element' (aka '(key: UUID, value: PersonViewModel)') has no member 'id'
```

But replacing `$person` with `$personList.persons[unchecked: personID]` would work.

---

Since the current way of passing a binding to an item in the collection  (`person: self.$personList.persons[unchecked: id])` works fine, I'm not sure about the benefits of passing the list and the identifier.

**Comment by trozware** [comment]
I feel it is more efficient to pass a single object instead of the entire list.
In this case, the list is small, but if the list is large, this might use up a lot of memory.

But thanks for taking the time to work out an alternative as this is definitely a gray area.
